### ISSUE TITLE
Implementar rotina de criação de usuário.

### ISSUE THREAD

**Issue by IagoRocha3112** [didatic20/ia-cidada#9]

**Comment by anacpbarros** [comment]
O que seria isso Iago? A página em si? Eu digo, o layout da página de cadastro?

**Comment by IagoRocha3112** [comment]
@anacpbarros  essa tarefa trata-se da implementação do código que fará uma requisição para o servidor (api) cadastrar um novo usuário. Sendo assim, essa tarefa depende da criação do formulário e do funcionamento efetivo da api.
